"use client"

import * as React from "react"
import Link from "next/link"
import { motion, AnimatePresence, useScroll, useTransform } from "framer-motion"
import { 
  Menu, 
  X, 
  ArrowRight, 
  Sparkles, 
  Layout, 
  Zap, 
  Github, 
  Twitter, 
  Linkedin, 
  Pencil, 
  Monitor,
  ChevronDown,
  ChevronRight,
  Plus
} from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Logo } from "@/components/logo"
import { cn } from "@/lib/utils"

export default function LandingPage() {
  const [isMenuOpen, setIsMenuOpen] = React.useState(false)
  const [activeFaq, setActiveFaq] = React.useState<number | null>(null)
  const { scrollYProgress } = useScroll()
  
  const backgroundY = useTransform(scrollYProgress, [0, 1], ["0%", "50%"])

  const navLinks = [
    { name: "Process", href: "#process" },
    { name: "Pricing", href: "/billing" },
    { name: "FAQ", href: "#faq" },
  ]

  const processSteps = [
    {
      icon: <Pencil className="size-6 text-primary" />,
      title: "1. Define Your Narrative",
      description: "Start with a simple text prompt or a detailed outline. Describe your vision, tone, and target audience."
    },
    {
      icon: <Sparkles className="size-6 text-blue-500" />,
      title: "2. Architect with AI",
      description: "Our AI engine analyzes your prompt and generates a structured, high-fidelity storyboard with professional layouts."
    },
    {
      icon: <Monitor className="size-6 text-indigo-500" />,
      title: "3. Refine & Present",
      description: "Tailor every detail in our real-time editor and export as HD PDF, images, or clean semantic code."
    }
  ]



  const faqs = [
    {
      question: "What makes Storyboard different from PowerPoint?",
      answer: "Storyboard is built specifically for architects and directors. Instead of starting with a blank slide, you start with a structured narrative generated by AI, wrapped in high-fidelity design tokens that follow professional agency standards."
    },
    {
      question: "Can I export the code for my slides?",
      answer: "Absolutely. Every slide you create is built with clean, semantic HTML and Tailwind CSS. You can export the raw code to integrate directly into your web projects or high-end presentation software."
    },
    {
      question: "Is the AI content customizable?",
      answer: "Yes. The AI provides the foundation, but you have total control over every element. You can tweak the copy, modify layouts, and refine every design token in our live editor."
    }
  ]

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.2
      }
    }
  }

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { type: "spring", stiffness: 100 } as const
    }
  }

  return (
    <div className="flex min-h-screen flex-col bg-background selection:bg-primary/20 scroll-smooth">
      <style jsx global>{`
        html { scroll-behavior: smooth; }
      `}</style>
      
      <motion.nav 
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/60 backdrop-blur-xl"
      >
        <div className="container mx-auto flex h-16 items-center justify-between px-6">
          <Link href="/">
            <Logo className="scale-75 transition-transform hover:scale-110" />
          </Link>

          <div className="hidden items-center gap-10 md:flex">
            {navLinks.map((link) => (
              <a 
                key={link.name} 
                href={link.href}
                className="text-[11px] font-semibold tracking-wider text-muted-foreground/60 transition-colors hover:text-foreground"
              >
                {link.name}
              </a>
            ))}
            <div className="ml-4 flex items-center gap-4">
              <Button variant="ghost" asChild className="h-8 px-4 text-[11px] font-semibold transition-all">
                <Link href="/login">Login</Link>
              </Button>
              <Button asChild className="h-8 px-5 bg-foreground text-background hover:bg-foreground/90 text-[11px] font-bold transition-all rounded-full">
                <Link href="/signup">Start Free</Link>
              </Button>
            </div>
          </div>

          <button 
            className="rounded-full p-2 hover:bg-muted md:hidden"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            {isMenuOpen ? <X className="size-5" /> : <Menu className="size-5" />}
          </button>
        </div>

        <AnimatePresence>
          {isMenuOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              className="border-t border-border/40 bg-background md:hidden shadow-2xl"
            >
              <div className="flex flex-col gap-4 p-8">
                {navLinks.map((link) => (
                  <a 
                    key={link.name} 
                    href={link.href}
                    onClick={() => setIsMenuOpen(false)}
                    className="text-lg font-black tracking-tight text-foreground/50 hover:text-primary transition-colors"
                  >
                    {link.name}
                  </a>
                ))}
                <div className="mt-6 flex flex-col gap-3">
                  <Button variant="outline" asChild className="w-full rounded-2xl h-12 font-bold border-border/60">
                    <Link href="/login">Login</Link>
                  </Button>
                  <Button asChild className="w-full rounded-2xl h-12 bg-primary font-bold">
                    <Link href="/signup">Get Started</Link>
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.nav>

      <main className="flex-1">
        <section className="relative flex flex-col items-center justify-center overflow-hidden px-6 py-32 md:py-48 lg:py-64">
          <motion.div 
            style={{ y: backgroundY }}
            className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none w-full"
          >
            <div className="absolute top-0 left-1/4 size-[500px] rounded-full bg-primary/10 blur-[150px]" />
            <div className="absolute bottom-0 right-1/4 size-[500px] rounded-full bg-blue-500/10 blur-[150px]" />
          </motion.div>

          <div className="container relative z-10 flex flex-col items-center text-center">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ type: "spring", damping: 15 }}
              className="mb-8 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-[10px] font-black uppercase tracking-[0.25em] text-primary shadow-sm"
            >
              <Sparkles className="size-3.5" />
              Intelligence meets aesthetics
            </motion.div>
            
            <motion.h1
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.8 }}
              className="max-w-4xl text-5xl font-bold leading-[1.1] tracking-tight sm:text-6xl md:text-7xl lg:text-8xl"
            >
              Build high-fidelity <br />
              <span className="text-muted-foreground/40">storyboards with AI.</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4, duration: 1 }}
              className="mt-8 max-w-lg text-base font-medium leading-relaxed text-muted-foreground/50 md:text-lg"
            >
              The AI engine for visual narratives. Architect professional storyboards with unprecedented precision and speed.
            </motion.p>

            <motion.div
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ delay: 0.6 }}
              className="mt-12"
            >
              <Button asChild size="lg" className="h-12 rounded-full px-10 text-sm font-medium bg-foreground text-background hover:bg-foreground/80 transition-all">
                <Link href="/signup">
                  Get Started
                </Link>
              </Button>
            </motion.div>
          </div>
        </section>

        <section id="process" className="py-24 md:py-40 border-t border-border/20 bg-muted/5 scroll-mt-24">
          <div className="container mx-auto px-6">
            <div className="mb-24 space-y-4 text-center mx-auto">
              <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-primary/60">The Engine</span>
              <h2 className="text-4xl font-bold tracking-tight md:text-5xl">Creative Workflow</h2>
              <p className="text-muted-foreground/40 text-base max-w-md mx-auto">A seamless path from concept to completion.</p>
            </div>
            
            <motion.div 
              variants={containerVariants}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-100px" }}
              className="grid grid-cols-1 gap-12 md:grid-cols-3"
            >
              {processSteps.map((step) => (
                <motion.div 
                  key={step.title}
                  variants={itemVariants}
                  className="flex flex-col gap-6"
                >
                  <div className="size-12 rounded-2xl bg-muted/30 border border-border/10 flex items-center justify-center">
                    {step.icon}
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-sm font-bold uppercase tracking-widest">{step.title}</h3>
                    <p className="text-muted-foreground/60 text-sm leading-relaxed font-medium">{step.description}</p>
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>



        <section id="faq" className="py-32 md:py-48 scroll-mt-24">
           <div className="container mx-auto px-6 max-w-3xl">
              <div className="mb-20 space-y-4">
                 <h2 className="text-3xl font-bold tracking-tight">Questions</h2>
                 <p className="text-muted-foreground/40 text-base">Quick answers to common inquiries.</p>
              </div>

              <div className="mx-auto">
                <Accordion type="single" collapsible className="w-full">
                  {faqs.map((faq, i) => (
                    <AccordionItem key={i} value={`item-${i}`} className="border-b border-border/10">
                      <AccordionTrigger className="text-base font-semibold tracking-tight py-6 hover:text-primary hover:no-underline">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="pb-8 text-muted-foreground/60 leading-relaxed text-base">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
           </div>
        </section>

        <section className="bg-neutral-950 py-32 md:py-56 relative overflow-hidden">
           <motion.div 
              animate={{ x: [0, 50, 0], y: [0, -30, 0] }}
              transition={{ duration: 10, repeat: Infinity }}
              className="absolute top-0 right-0 size-[600px] bg-primary/10 rounded-full blur-[150px] -mr-64 -mt-64" 
            />
           
           <div className="container relative z-10 mx-auto px-6 text-center">
              <div className="max-w-2xl mx-auto space-y-10">
                <motion.h2 
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  className="text-4xl font-bold tracking-tight md:text-6xl text-white"
                >
                  Start your next <br />
                  <span className="text-white/20">storyboard today.</span>
                </motion.h2>
                <p className="text-white/30 text-base max-w-sm mx-auto leading-relaxed">
                  Join the architects and directors transforming their visual workflow.
                </p>
                <div className="pt-6">
                  <Button asChild size="lg" className="h-12 rounded-full px-10 text-sm font-bold bg-white text-black hover:bg-white/90 transition-all">
                    <Link href="/signup">Start Free Access</Link>
                  </Button>
                </div>
              </div>
           </div>
        </section>
      </main>

      <footer className="border-t border-border/10 bg-background py-20">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 pb-16 border-b border-border/5">
            <div className="col-span-1 md:col-span-2">
              <Logo className="scale-75 -ml-2 mb-6 opacity-80" />
              <p className="text-sm text-muted-foreground/60 max-w-sm leading-relaxed mb-8">
                The ultimate platform for high-density visual storyboard narratives. 
                Architecting stories with professional precision at scale.
              </p>
              <div className="flex gap-4">
                {[
                  { icon: <Twitter className="size-4" />, href: "#" },
                  { icon: <Linkedin className="size-4" />, href: "#" },
                  { icon: <Github className="size-4" />, href: "#" }
                ].map((social, i) => (
                  <Link 
                    key={i} 
                    href={social.href}
                    className="size-9 rounded-full border border-border/40 flex items-center justify-center text-muted-foreground hover:text-foreground hover:border-foreground transition-all"
                  >
                    {social.icon}
                  </Link>
                ))}
              </div>
            </div>
            
            <div>
              <h4 className="text-[10px] font-bold uppercase tracking-[0.3em] text-foreground mb-6">Product</h4>
              <nav className="flex flex-col gap-4">
                <Link href="/templates" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">Design Library</Link>
                <Link href="/billing" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">Pricing Plans</Link>
                <Link href="#" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">Showcase</Link>
              </nav>
            </div>

            <div>
              <h4 className="text-[10px] font-bold uppercase tracking-[0.3em] text-foreground mb-6">Company</h4>
              <nav className="flex flex-col gap-4">
                <Link href="#" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">About Us</Link>
                <Link href="#" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">Privacy Policy</Link>
                <Link href="#" className="text-[13px] text-muted-foreground hover:text-foreground transition-colors">Terms of Service</Link>
              </nav>
            </div>
          </div>
          
          <div className="flex flex-col items-center justify-between gap-6 pt-12 text-center md:flex-row md:text-left">
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-muted-foreground/30">
              © 2026 Storyboard Architect Inc. All rights reserved.
            </p>
            <div className="flex gap-8 text-[10px] font-bold uppercase tracking-[0.3em] text-muted-foreground/20">
              <Link href="#" className="hover:text-foreground transition-colors">Instagram</Link>
              <Link href="#" className="hover:text-foreground transition-colors">Dribbble</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}




