export const RECOMMENDED_PROMPTS = [
  "The future of sustainable urban farming in neon-lit mega cities.",
  "A cinematic journey through the Silk Road in the year 2088.",
  "The daily life of a deep-sea maintenance crew in an underwater base.",
  "A high-stakes heist on a floating casino in the clouds.",
  "The evolution of healthcare: Nanobots and biological 3D printing.",
  "A post-apocalyptic scavenger's find: An intact library of ancient seeds.",
  "The first manned mission to Proxima Centauri: Arrival at the planet.",
  "A cyber-noir detective case involving a missing AI personality.",
  "The annual floating lantern festival in a coastal village of spirits.",
  "A desert colony where water is managed by a sentient crystal.",
  "The rise and fall of a billionaire who built a city on Mars.",
  "A peaceful coexistence between humans and giant bioluminescent beasts.",
  "The secret underground markets of a strictly regulated data-economy.",
  "A vertical forest skyscraper complex in the heart of Tokyo.",
  "The discovery of an ancient alien portal buried under the Antarctic ice.",
  "A solar-punk revolution where technology mimics the efficiency of plants.",
  "The training academy for elite pilots of interdimensional vehicles.",
  "A world where dreams can be recorded and traded like stocks.",
  "The terraforming process of Venus: Turning poison into paradise.",
  "A steampunk expedition to the center of the Earth.",
  "The aesthetic of zero-gravity architecture: Habitats in orbit.",
  "A futuristic Olympics featuring augmented human athletes.",
  "The restoration of the Great Barrier Reef using robotic coral.",
  "A digital afterlife where consciousness is uploaded to a server.",
  "The first contact with a hive-mind species in deep space.",
  "A nomadic tribe traveling across the crystalline plains of Europa.",
  "The infrastructure of a lunar mining colony: Tunnels and oxygen hubs.",
  "A world where every person has a personalized AI guardian.",
  "The art of orbital sculpture: Massive works visible from Earth.",
  "A high-speed transit system connecting all continents via vacuum tubes.",
  "The transformation of abandoned oil rigs into luxury marine resorts.",
  "A bioluminescent rainforest where the trees communicate via light.",
  "The logistics of a space elevator transporting cargo to orbit.",
  "A futuristic library where books are holograms and knowledge is inhaled.",
  "The design of a ship that travels through the sun's corona.",
  "A society living inside a massive hollowed-out asteroid.",
  "The impact of a comet hitting the Pacific Ocean: Evacuation plans.",
  "A futuristic fashion show where clothes are made of living fabric.",
  "The architecture of a city built entirely out of recycled ocean plastic.",
  "A summit of leaders from artificial planetary systems.",
  "The day a rogue planet passed through our solar system.",
  "A research station on a gas giant floating amongst the clouds.",
  "The creation of a synthetic ecosystem to replace a lost biosphere.",
  "A world where gravity can be toggled in specific zones.",
  "The pilgrimage to the Edge of the Universe observatory.",
  "A futuristic courtroom where the judge is a neural network.",
  "The construction of a multi-generational ship for interstellar travel.",
  "A hidden city protected by a massive holographic waterfall.",
  "The evolution of communication: Telepathy through neural implants.",
  "A day in the life of a janitor in a high-tech orbital museum."
];
