export const RECOMMENDED_PROMPTS = [
  "Q3 Strategic Roadmap for a Silicon Valley AI startup focusing on ethical model governance and sustainable GPU infrastructure.",
  "Digital Transformation Strategy 2026: Navigating the shift from legacy banking to decentralised finance ecosystems.",
  "The Circular Economy in Global Logistics: Reducing carbon footprint through AI-driven route optimisation and biodegradable packaging.",
  "Market Entry Analysis: Launching a sustainable D2C wellness brand in the APAC region with a focus on Gen Z consumer behavior.",
  "Cybersecurity Resilience Report: Protecting critical infrastructure against quantum-computing enabled threat actors in the energy sector.",
  "The Future of Remote Work: Designing hybrid environments that balance employee well-being with high-performance operational output.",
  "Precision Medicine and Genomic Data: How CRISPR and AI are revolutionising oncology treatments by 2030.",
  "Renewable Energy Transition in Emerging Markets: Financing the shift from coal to hydrogen and solar in Southeast Asia.",
  "Luxury Retail in the Metaverse: Fusing physical craftsmanship with digital scarcity to create new customer loyalty loops.",
  "Smart City Infrastructure: Integrating IoT sensors and real-time data analytics to solve urban traffic congestion and waste management.",
  "The Evolution of Venture Capital: Data-driven scouting and the rise of decentralized autonomous organizations (DAOs) in seed funding.",
  "Food Security and Vertical Farming: Scaling indoor agriculture to support mega-cities in arid climates like the Middle East.",
  "ESG Reporting for Global Manufacturers: Moving beyond compliance to create genuine social impact in the supply chain.",
  "Educational Technology (EdTech) 2.0: Personalized learning paths through neural-network based adaptive curriculum design.",
  "The Blue Economy: Sustainable management of ocean resources for economic growth and improved ecosystem health.",
  "Industrial Automation and Robotics: The transformation of the workforce in the age of collaborative robots (cobots).",
  "FinTech Disruption: The role of Central Bank Digital Currencies (CBDCs) in the future of global cross-border payments.",
  "Sustainable Fashion Supply Chains: From fiber to garment with 100% transparency using blockchain tracking.",
  "The Space Economy: Logistics of lunar mining and the commercialization of low Earth orbit (LEO) for satellite networks.",
  "Aviation Decarbonization: The roadmap to net-zero through Sustainable Aviation Fuels (SAF) and hydrogen-powered flight.",
  "Generative AI in the Creative Industries: Opportunities and ethical challenges for design, music, and filmmaking agencies.",
  "Next-Generation Semiconductor Manufacturing: The race for 2nm process nodes and the geopolitics of the global chip supply.",
  "Electric Vehicle (EV) Infrastructure: Scaling fast-charging networks and battery recycling programs to meet 2035 targets.",
  "Privacy in the Age of Big Data: Implementing Zero-Knowledge Proofs (ZKP) and Differential Privacy in consumer applications.",
  "Advanced Material Science: Carbon nanotubes and graphene applications in aerospace and high-performance computing.",
  "The Future of Insurance: Parametric models and real-time risk assessment in an era of climate volatility.",
  "MedTech Innovation: Tele-surgery and remote patient monitoring using 5G and low-latency haptic feedback.",
  "AgTech 3.0: Autonomous tractors and satellite-monitored crop health to increase yields with 40% less water usage.",
  "Global E-commerce Logistics: Solving the last-mile delivery challenge through drone swarms and automated delivery hubs.",
  "Clean Water Access: Deployment of atmospheric water generators and large-scale desalination in stressed regions.",
]
