// Import structured interface types bridging HTML blocks back to Application Editor standards
import { Slide, SlideElement } from "@/types/editor"
// Import CSS formatting utility translating variable types into predictable exports
import { colorToHex } from "./utils"

/**
 * Interface representing the direct raw result structures generated by the conversational LLM.
 */
export interface HtmlSlide {
  id: number // System assigned temporary identifier
  index: number // Linear order configuration position mapping
  title: string // Headline text extraction
  html: string // Complete raw LLM-generated string representing the slide HTML sequence
  prompt?: string // Original source text mapped mapping input constraints
  content?: string // Secondary parameter data definitions mappings
  structuredSlide?: Slide // Optional structured version recursively populated during translation sequences
}

/**
 * Wrapper object mapping an entire linear generated presentation data dictionary
 */
export interface StoryboardData {
  title: string // Auto-summarized representation title
  slides: HtmlSlide[] // Linked sequential LLM blocks representations
}

/**
 * Converts AI-generated HTML slide into structured Slide elements
 * for better native exports (PPTX, PDF).
 * Using off-screen rendering for accurate coordinate and style extraction.
 */
export async function htmlToStructuredSlide(
  htmlSlide: HtmlSlide
): Promise<Slide> {
  // If we already have structured data from the AI parser cached locally, use it efficiently bypassing layout sweeps!
  if (htmlSlide.structuredSlide) {
    return htmlSlide.structuredSlide
  }

  // Prevent phantom rendering execution exceptions occurring during Next.js SSR backend builds
  if (typeof window === "undefined") {
    // Return empty fallback representation schema to prevent complete initialization crashes
    return {
      id: htmlSlide.id,
      elements: [],
      bgColor: "#ffffff",
      layout: "free",
    }
  }

  // Generate an invisible DOM fragment root specifically used to securely render active physical styling definitions
  const container = document.createElement("div")

  // Apply specific strict style override forcing the block off-screen and hiding overflow
  Object.assign(container.style, {
    position: "fixed",
    top: "0",
    left: "-20000px", // Safely push layout entirely out of physical user viewport
    width: "1024px", // Force strict expected canvas measurement bounds
    height: "576px", // Force strict expected canvas measurement bounds
    zIndex: "-1",
    overflow: "hidden", // Clamp parameters
  })

  // Physically append the raw HTML into the isolated container node wrapper mapping
  container.innerHTML = `
      <div id="capture-root" style="width: 1024px; height: 576px; position: relative; overflow: hidden; background: white; margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif;">
          <style>
              * { box-sizing: border-box !important; }
              body, html { margin: 0; padding: 0; background: white; width: 1024px; height: 576px; }
          </style>
          ${htmlSlide.html}
      </div>
  `

  // Tell the browser rendering engine to explicitly map the object resolving dimensions and CSS cascades
  document.body.appendChild(container)
  // Define wait timeout yielding engine priority executing render repaints correctly capturing positions
  await new Promise((resolve) => setTimeout(resolve, 200))

  // Find mounted specific wrapper root target representing strict active viewport
  const root = container.querySelector("#capture-root") as HTMLElement
  // Initialize aggregation map collection definitions
  const elements: SlideElement[] = []

  // Default base fallback properties
  let bgColor = "#ffffff"
  let bgImage = ""

  /**
   * Recursive tree walking logic tracking computed background layer values dynamically through nodes
   */
  const findBackground = (
    node: HTMLElement
  ): { color?: string; image?: string } => {
    // Probe physical active CSS computed variables map properties
    const computed = window.getComputedStyle(node)
    // Extract base formatted parameter states
    let color = colorToHex(computed.backgroundColor)
    let image = ""

    // Check mapping parameter bindings manually
    const bg = computed.backgroundImage
    // Evaluate if valid configuration property flag exists
    if (bg && bg !== "none") {
      if (bg.includes("url")) {
        // Run regex parsing target resource location source
        const match = bg.match(/url\(["']?(.*?)["']?\)/)
        if (match) image = match[1] // Apply mapping string directly
      } else if (bg.includes("gradient")) {
        // Run regex mapping hex color abstraction
        const colorMatch = bg.match(
          /#(?:[0-9a-fA-F]{3}){1,2}|rgb\(.*?\)|rgba\(.*?\)/
        )
        if (colorMatch) color = colorToHex(colorMatch[0]) // Fallback resolving generic color references mapping
      }
    }

    // Validate visibility mapping threshold filters dropping defaults
    const isMeaningful =
      color &&
      color !== "rgba(0, 0, 0, 0)" &&
      color !== "transparent" &&
      color !== "#00000000"

    // Return early resolution context
    if (isMeaningful || image)
      return { color: isMeaningful ? color : undefined, image }

    // Walk down DOM hierarchy iteratively finding nested block attributes map mappings
    for (const child of Array.from(node.children)) {
      if (child instanceof HTMLElement) {
        // Recursively trigger nested checks mapping node hierarchies definitions
        const childBg = findBackground(child)
        if (childBg.color || childBg.image) return childBg
      }
    }
    return {}
  }

  // Assign calculated generic root parameter bindings parsing
  const bgRes = findBackground(root)
  if (bgRes.color) bgColor = bgRes.color
  if (bgRes.image) bgImage = bgRes.image

  // Record core bounding representation container mapping offsets
  const rootRect = root.getBoundingClientRect()

  /**
   * Primary configuration mapping traverse loop logic generating abstract standard element node representation
   */
  const traverse = (node: Element) => {
    // Safely exit parsing string variables elements constraints
    if (!(node instanceof HTMLElement)) return
    // Eliminate layout blocking meta abstraction configuration blocks mappings
    if (node.tagName === "STYLE" || node.tagName === "SCRIPT") return

    // Compute strict DOM dimensional bounds offsets
    const rect = node.getBoundingClientRect()
    // Resolve computed physics cascaded properties mapping
    const style = window.getComputedStyle(node)

    // Abstract offset logic matching physical layout bounding positioning limits
    const x = Math.max(0, rect.left - rootRect.left)
    const y = Math.max(0, rect.top - rootRect.top)
    const width = rect.width
    const height = rect.height

    // Precondition filters checking HTML standard primitives flags configurations
    const isImage = node.tagName === "IMG"
    const textTags = [
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
      "P",
      "SPAN",
      "DIV",
      "LI",
      "B",
      "I",
      "STRONG",
      "EM",
    ]
    // Filter validation checking physical content variables existing correctly logic rules
    const hasText = Array.from(node.childNodes).some(
      (n) => n.nodeType === 3 && n.textContent?.trim().length
    )

    // Layout processing mapping logic variables generating SlideElement shapes dynamically
    if (isImage) {
      elements.push({
        id: Math.random().toString(36).substr(2, 9), // Inject temp configuration bindings logic
        type: "image", // Target layout object mapping definition
        src: (node as HTMLImageElement).src, // Link source file data definitions
        x,
        y,
        width: width || 400, // Format bounds
        height: height || 300, // Format bounds
        objectFit: (style.objectFit as "cover" | "contain" | "fill") || "cover", // Resolve style
      })
    } else if (textTags.includes(node.tagName) && hasText) {
      // Decode content stripping standard whitespace constraints handling
      const content = (node as HTMLElement).innerText.trim()
      if (content) {
        elements.push({
          id: Math.random().toString(36).substr(2, 9), // Create deterministic layout index
          type: "text", // Resolve explicitly node properties definition shapes
          content,
          x,
          y,
          width: width || rect.width, // Pull explicit dimensions mappings
          height: height || rect.height,
          fontSize: parseInt(style.fontSize) || 24, // Resolve CSS dimensions sizes metrics integers
          color: colorToHex(style.color || "#000000"), // Clean property strings constraints values formatting
          fontWeight: style.fontWeight || "normal", // Translate logic
          textAlign: (style.textAlign as "left" | "center" | "right") || "left", // Provide alignment bindings
          fontFamily:
            style.fontFamily?.replace(/['"]/g, "") || "Inter, sans-serif", // Clean system font quotes representations formats
        })
      }
    } else if (node.tagName === "DIV" || node.tagName === "SPAN") {
      // Create explicit shape element structures for complex physical block containers
      const bg = colorToHex(style.backgroundColor)
      // Evaluate visible properties threshold limits configurations
      const hasBg =
        bg &&
        bg !== "rgba(0, 0, 0, 0)" &&
        bg !== "transparent" &&
        bg !== "#00000000"

      // Prevent phantom overlaps configurations blocks mappings overlapping physical logic spaces
      if (hasBg && width > 0 && height > 0 && !hasText) {
        elements.push({
          id: Math.random().toString(36).substr(2, 9),
          type: "shape",
          shapeType: "rectangle",
          x,
          y,
          width,
          height,
          color: bg,
          opacity: parseFloat(style.opacity) || 1, // Extract physical CSS state mapping natively into format definition
        })
      }
    }

    // Evaluate deeper recursive sub-tree configuration mapping arrays processing layout dynamically
    if (!isImage) Array.from(node.children).forEach((child) => traverse(child))
  }

  // Begin layout sweeping processing routines mapped sequence
  traverse(root)
  // Clean phantom DOM layout components out avoiding memory leaking configuration paths
  document.body.removeChild(container)

  // Final mapped translation structure exported sequence natively into app definitions limits shapes
  return { id: htmlSlide.id, elements, bgColor, bgImage, layout: "free" }
}

/**
 * Parses raw text logic strings mapping out valid `<slide-X>` layout blocks representations.
 */
export function parseStoryboard(text: string): StoryboardData {
  // Define fallback target structural wrapper container state mapped limits
  const result: StoryboardData = { title: "Advanced Storyboard", slides: [] }

  // Logic mapping extracting custom string variables representation parameters natively definitions limits
  let titleMatch
  // Define regex capturing arbitrary length presentation titles
  const titleRegex = /<title[^>]+name=["'](.*?)["']/g
  let lastTitle
  // Scan mapping loop targeting strings execution expressions variables
  while ((titleMatch = titleRegex.exec(text)) !== null) {
    lastTitle = titleMatch[1]
  }
  // Inject metadata
  if (lastTitle) result.title = lastTitle

  // Defining advanced regular expression isolating distinct sequence blocks containing explicit configurations structures mapping values variables shapes HTML targets variables
  const slideRegex =
    /<(slide-(\d+))\s+title=["'](.*?)["'][^>]*>([\s\S]*?)<\/\1>/g
  let match

  // Process mapping constraints scanning iterations natively string limits blocks
  while ((match = slideRegex.exec(text)) !== null) {
    // Decode mappings targets expressions values properties mapped sequences
    const id = parseInt(match[2])
    const title = match[3]
    const content = match[4].trim()

    // Pass data values explicit targets mapping logic boundaries format limits
    const html = content
    const structuredSlide = undefined

    // Inject configuration updating mappings existing arrays boundaries blocks values
    const existingIndex = result.slides.findIndex((s) => s.id === id)
    if (existingIndex !== -1) {
      result.slides[existingIndex] = {
        id,
        index: id,
        title,
        html,
        structuredSlide,
      }
    } else {
      // Prepend layouts explicit data variables shape structures maps sequences appending values
      result.slides.push({ id, index: id, title, html, structuredSlide })
    }
  }

  // Sequence chronological index properties values arrays logic blocks limits
  result.slides.sort((a, b) => a.id - b.id)
  return result
}
